name: flameproject
description: practicing game development in flutter

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flame: ^0.19.0
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:
  #assets:
   #- images/a_dot_burr.jpeg
   #- images/a_dot_ham.jpeg
  uses-material-design: true





























